# Generated by Django 5.2.5 on 2025-08-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='kilometraje',
            field=models.PositiveIntegerField(default=1, verbose_name='Kilometraje al momento del Mantenimiento'),
            preserve_default=False,
        ),
    ]
