# Generated by Django 5.2.5 on 2025-08-20 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0002_ordentrabajo_kilometraje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tanqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha y Hora del Tanqueo')),
                ('kilometraje', models.PositiveIntegerField(verbose_name='Kilometraje')),
                ('galones', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Galones')),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Total ($)')),
                ('conductor', models.CharField(blank=True, max_length=150, null=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flota.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Registro de Tanqueo',
                'verbose_name_plural': 'Registros de Tanqueo',
                'ordering': ['-fecha'],
            },
        ),
    ]
