# Generated by Django 5.2.5 on 2025-08-25 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0003_tanqueo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Plan')),
                ('tipo_motor', models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIESEL', 'Diesel')], max_length=10, verbose_name='Tipo de Motor')),
                ('intervalo_km', models.PositiveIntegerField(verbose_name='Intervalo (km)')),
            ],
            options={
                'verbose_name': 'Plan de Mantenimiento',
                'verbose_name_plural': 'Planes de Mantenimiento',
            },
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_motor',
            field=models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIESEL', 'Diesel')], default='GASOLINA', max_length=10),
        ),
        migrations.CreateModel(
            name='EstadoMantenimiento',
            fields=[
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='flota.vehiculo')),
                ('km_ultimo_mantenimiento', models.PositiveIntegerField(default=0)),
                ('km_proximo_mantenimiento', models.PositiveIntegerField(default=0)),
                ('ultimo_plan_realizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flota.planmantenimiento')),
            ],
            options={
                'verbose_name': 'Estado de Mantenimiento',
                'verbose_name_plural': 'Estados de Mantenimiento',
            },
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='plan_aplicado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flota.planmantenimiento', verbose_name='Plan de Mantenimiento Aplicado'),
        ),
        migrations.CreateModel(
            name='TareaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción de la Tarea')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='flota.planmantenimiento')),
            ],
            options={
                'verbose_name': 'Tarea del Plan',
                'verbose_name_plural': 'Tareas del Plan',
            },
        ),
    ]
