# Generated by Django 5.2.5 on 2025-08-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0004_planmantenimiento_vehiculo_tipo_motor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCorrectiva',
            fields=[
            ],
            options={
                'verbose_name': 'Orden de Mantenimiento Correctivo',
                'verbose_name_plural': 'Órdenes de Mantenimiento Correctivo',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('flota.ordentrabajo',),
        ),
        migrations.CreateModel(
            name='OrdenPreventiva',
            fields=[
            ],
            options={
                'verbose_name': 'Orden de Mantenimiento Preventivo',
                'verbose_name_plural': 'Órdenes de Mantenimiento Preventivo',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('flota.ordentrabajo',),
        ),
    ]
