# Generated by Django 5.2.5 on 2025-08-25 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0005_ordencorrectiva_ordenpreventiva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='plan_aplicado',
        ),
        migrations.RemoveField(
            model_name='estadomantenimiento',
            name='ultimo_plan_realizado',
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorías de Mantenimiento'},
        ),
        migrations.AlterModelOptions(
            name='estadomantenimiento',
            options={'verbose_name_plural': 'Estados de Mantenimiento'},
        ),
        migrations.AlterModelOptions(
            name='modofalla',
            options={'verbose_name_plural': 'Modos de Falla'},
        ),
        migrations.AlterModelOptions(
            name='ordencorrectiva',
            options={'verbose_name_plural': 'Órdenes de Mantenimiento Correctivo'},
        ),
        migrations.AlterModelOptions(
            name='ordenpreventiva',
            options={'verbose_name_plural': 'Órdenes de Mantenimiento Preventivo'},
        ),
        migrations.AlterModelOptions(
            name='ordentrabajo',
            options={'verbose_name_plural': 'Órdenes de Trabajo'},
        ),
        migrations.AlterModelOptions(
            name='subcategoria',
            options={'verbose_name_plural': 'Subcategorías'},
        ),
        migrations.AlterModelOptions(
            name='tanqueo',
            options={'ordering': ['-fecha'], 'verbose_name_plural': 'Registros de Tanqueo'},
        ),
        migrations.AddField(
            model_name='estadomantenimiento',
            name='km_activacion',
            field=models.PositiveIntegerField(default=0, help_text='Kilometraje en el que se activó el plan por primera vez.'),
        ),
        migrations.AlterField(
            model_name='estadomantenimiento',
            name='km_proximo_mantenimiento',
            field=models.PositiveIntegerField(default=0, help_text='Kilometraje calculado para el próximo servicio preventivo (cada 10.000km).'),
        ),
        migrations.AlterField(
            model_name='estadomantenimiento',
            name='km_ultimo_mantenimiento',
            field=models.PositiveIntegerField(default=0, help_text='Kilometraje del último mantenimiento preventivo completado.'),
        ),
        migrations.AlterField(
            model_name='historialvehiculo',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historialvehiculo',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historialvehiculo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historialvehiculo',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flota.vehiculo'),
        ),
        migrations.AlterField(
            model_name='intervencion',
            name='modo_falla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='flota.modofalla'),
        ),
        migrations.AlterField(
            model_name='intervencion',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intervencion',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flota.subcategoria'),
        ),
        migrations.AlterField(
            model_name='modofalla',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='modofalla',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flota.subcategoria'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='kilometraje',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flota.vehiculo'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flota.categoria'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tanqueo',
            name='costo_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tanqueo',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tanqueo',
            name='galones',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='tanqueo',
            name='kilometraje',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tanqueo',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flota.vehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='año',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flota.zona'),
        ),
        migrations.DeleteModel(
            name='TareaPlan',
        ),
        migrations.DeleteModel(
            name='PlanMantenimiento',
        ),
    ]
