# Generated by Django 5.2.5 on 2025-08-25 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0006_remove_ordentrabajo_plan_aplicado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoOrdenCorrectiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(verbose_name='Comentario / Novedad')),
                ('fecha_entrega_estimada', models.DateTimeField(verbose_name='Nueva Fecha de Entrega Estimada')),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='flota.ordencorrectiva')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Seguimiento de Orden',
                'verbose_name_plural': 'Seguimientos de la Orden',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
    ]
