# Generated by Django 5.2.5 on 2025-08-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0007_seguimientoordencorrectiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='lugar_mantenimiento',
            field=models.CharField(choices=[('TALLER_CARTAGENA', 'Taller Cartagena'), ('TALLER_CAUCASIA', 'Taller Caucasia'), ('TERCERO', 'Tercero')], default='TALLER_CARTAGENA', max_length=20, verbose_name='Lugar del Mantenimiento'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='nombre_tercero',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Taller/Mecánico Tercero'),
        ),
    ]
